# Catppuccin theme for tmux
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Disable automatic renaming of windows
setw -g automatic-rename off

# Enable mouse support
set -g mouse on

# Session/window navigation
bind-key -n C-Up  switch-client -p
bind-key -n C-Down  switch-client -n
bind-key -n C-Left  previous-window
bind-key -n C-Right next-window
