# Automatically rename windows based on running command
set-option -g automatic-rename on

# Enable auto focus
set -g focus-events on

# Enable mouse support
set -g mouse on

# Session/window navigation
bind-key -n C-Left  previous-window
bind-key -n C-Right next-window

# Theme
source-file ~/.config/tmux/theme.conf
